### PR TITLE
Bugfix/uibugs

### PR DESCRIPTION
**Pull request by FraTheVet**
proposal on approach to fix existing ui bugs and improve registration form structure

### CODE REVIEW

**Review by geriskenderi — APPROVED** [review]
Very good comrade, the cause approves your homepage ui fixes 🔴

**Review by geriskenderi — DISMISSED** [review]
Looks very useful for the events part of the form. The cause approves these changes 🔴

**Comment by FraTheVet** [comment]
Not so fast comrade, I must've messed up the social icons at the bottom of the page, probably changing html font-size unit. Looking into it

**Review by GiacoAndCo — DISMISSED** [review]

**Comment by FraTheVet** [comment]
imma do the admin of the situation and merge anyways due to time constraints

**Pull request merged**
