### PR TITLE
feature/dockerization

### PR DESCRIPTION
**Pull request by mondial7**

### CODE REVIEW

**Comment by mondial7** [comment]
@FraTheVet & @GiacoAndCo I have the feeling some cat jumped  on that node_baseT 🤷‍♂️💕

**Comment by mondial7** [comment]
While testing the branch on my machine I faced some issues running the local dev webserver. The problem (as in the picture) fails to run the webserver.
image

It won't actually log anything on the console when you start the container. E.g.
image

In fact, I believe it's due to the local node_modules currently on my machine since I was working on a different branch before checking out dockerization. That is, the `npm install` won't force a clean install of already existing packages.

**.....** I removed node_modules/ and package-lock.json before running up node_install and webserver. Unfortunately, while running on my windows machine the rm -rf command launched inside the container rise issues, so I couldn't use a `npm run install:clean` but I had to remove the file and the folder manually outside the containers.
Now the new error when running `docker-compose up node_install` is:
```
node_install_1  \|                                                                
node_install_1  \| npm ERR! Maximum call stack size exceeded                      
node_install_1  \|
--


```

**Comment by GiacoAndCo** [comment]
I agree on removing `package-lock.json` and `node_modules` after node_base is done. It still builds up every time it launches: this in return might prolong the time it needs to actually start. I guess we could also add them to a `.dockerignore` file, but I'll wait further confirmations.

Another idea would be to use [Docker's layers](http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js/), by copying just the `package.json` inside the newly created container, and letting it build up the necessary modules before copying the actual application. This would need some tinkering due to the fact that we use volumes, but it doesn't look impossible.

**Comment by riccardofelluga** [comment]
I've tested the dockerisation on macOS and it shows the same behavior as @mondial7 experienced. To solve the issue I suggest to avoid sharing the whole folder with the docker image and, instead, share only the `src/` folder and the config files (like `package.json`). I hope this can be helpful to address the issue.

**Comment by GiacoAndCo** [comment]
Fixed the 'node_modules' issue by adding a script that deletes the folder and 'package-lock.json' prior to installing. @mondial7 can you please try it? 
As far as the Maximum call stack exceeded I don't think it's an issue of the docker-compose itself, but more of a docker-on-Windows issue.

Since we are setting up Jenkins I've added a simpler dockerfile, but I'd keep both for developing.

**Comment by FraTheVet** [comment]
Closing PR as dockerization will primarily focus on integrating with CI, will reopen after integration of Jenkins

**Pull request closed without merging**
